apiVersion: batch/v1
kind: CronJob
metadata:
  name: ce-nrcan-demo
spec:
  schedule: "*/2 * * * *"  # Every 2 minutes!
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
