apiVersion: batch/v1beta1  # apiVersion: batch/v1 on GKE 1.21+
kind: CronJob
metadata:
  name: ce-nrcan-demo
spec:
  schedule: "*/2 * * * *"  # Every 2 minutes!
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ce-nrcan-demo
            image: gcr.io/ce-nrcan-demo/ce-nrcan-demo
            imagePullPolicy: Always
          restartPolicy: Never
