apiVersion: batch/v1beta1  # apiVersion: batch/v1 on GKE 1.21+
kind: CronJob
metadata:
  name: ce-nrcan-demo
  namespace: default
spec:
  schedule: "0 0 0 0 0"  # Every 5 minutes!
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ce-nrcan-demo
            image: gcr.io/ce-nrcan-demo/ce-nrcan-demo:latest
            imagePullPolicy: Always
            env:
              - name: "GOOGLE_APPLICATION_CREDENTIALS"
                value: "/var/run/secret/cloud.google.com/service-account.json"
            volumeMounts:
              - mountPath: "/var/run/secret/cloud.google.com"
                name: "service-account"
          volumes:
            - name: "service-account"
              secret:
                secretName: "sa-json"
          restartPolicy: OnFailure
